"""
Synthesis Skill
================
Contains the prompt-construction and structured-output-parsing logic used by
the orchestrator to synthesize raw specialist agent outputs into the final
5-section intelligence report.

Design:
  - `build_synthesis_prompt()` → crafts the Gemini prompt from aggregated data
  - `parse_synthesis_response()` → robustly extracts the 5 sections from the LLM output
  - `SynthesisInput` / `IntelligenceReport` → typed data models for clean handoffs
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class SynthesisInput:
    """
    Aggregated outputs from all three specialist agents.
    Passed to the synthesis skill to produce the final report.
    """
    query: str
    drug_class: str
    indication: str
    time_window: str
    articles: list[dict[str, Any]] = field(default_factory=list)
    trials: list[dict[str, Any]] = field(default_factory=list)
    fda_approvals: list[dict[str, Any]] = field(default_factory=list)
    adverse_events: list[dict[str, Any]] = field(default_factory=list)
    drug_labels: list[dict[str, Any]] = field(default_factory=list)


@dataclass
class IntelligenceReport:
    """
    The final 5-section competitive intelligence report.
    All sections are plain-text summaries generated by the LLM.
    """
    query: str
    generated_at: str
    drug_class: str
    indication: str
    # The five sections
    research_landscape: str = ""
    clinical_pipeline: str = ""
    regulatory_status: str = ""
    competitive_summary: str = ""
    strategic_outlook: str = ""
    # Metadata
    data_sources: dict[str, int] = field(default_factory=dict)
    raw_response: str = ""


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def _summarize_articles(articles: list[dict]) -> str:
    """Format top articles for inclusion in the synthesis prompt."""
    if not articles:
        return "No relevant PubMed articles retrieved."
    lines = []
    for i, a in enumerate(articles[:8], 1):
        lines.append(
            f"{i}. [{a.get('pub_date', 'N/A')}] {a.get('title', 'N/A')} "
            f"— {a.get('authors', 'N/A')} — {a.get('journal', 'N/A')} "
            f"(PMID: {a.get('pmid', 'N/A')})"
        )
    return "\n".join(lines)


def _summarize_trials(trials: list[dict]) -> str:
    """Format top trials for inclusion in the synthesis prompt."""
    if not trials:
        return "No clinical trials retrieved."
    lines = []
    for i, t in enumerate(trials[:8], 1):
        lines.append(
            f"{i}. {t.get('nct_id', 'N/A')} | Phase: {t.get('phase', 'N/A')} "
            f"| Status: {t.get('status', 'N/A')} | Sponsor: {t.get('sponsor', 'N/A')} "
            f"| Enrollment: {t.get('enrollment', 'N/A')} "
            f"| Endpoint: {t.get('primary_endpoint', 'N/A')[:80]}"
        )
    return "\n".join(lines)


def _summarize_fda(approvals: list[dict], adverse_events: list[dict], labels: list[dict]) -> str:
    """Format FDA data for inclusion in the synthesis prompt."""
    parts = []

    if approvals:
        parts.append("FDA APPROVALS:")
        for a in approvals[:4]:
            parts.append(
                f"  • {a.get('application_number', 'N/A')} ({a.get('application_type', 'N/A')}) "
                f"| Sponsor: {a.get('sponsor', 'N/A')} "
                f"| Brands: {', '.join(a.get('brand_names', []))}"
            )
    else:
        parts.append("FDA APPROVALS: No approval records retrieved.")

    if adverse_events:
        parts.append("\nTOP ADVERSE EVENTS (FAERS):")
        for ae in adverse_events[:5]:
            parts.append(f"  • {ae.get('reaction', 'N/A')}: {ae.get('count', 'N/A')} reports")
    else:
        parts.append("\nADVERSE EVENTS: No FAERS data retrieved.")

    if labels:
        parts.append("\nDRUG LABEL HIGHLIGHTS:")
        label = labels[0]
        parts.append(f"  • Brand: {label.get('brand_name', 'N/A')}")
        moa = label.get('mechanism_of_action', 'N/A')
        if moa and moa != 'N/A':
            parts.append(f"  • MOA: {moa[:200]}")
        ind = label.get('indications_and_usage', 'N/A')
        if ind and ind != 'N/A':
            parts.append(f"  • Indications: {ind[:200]}")

    return "\n".join(parts)


def build_synthesis_prompt(data: SynthesisInput) -> str:
    """
    Construct the Gemini synthesis prompt from all specialist agent outputs.

    The prompt instructs the LLM to produce exactly 5 labelled sections
    so that `parse_synthesis_response()` can extract them reliably.
    """
    articles_text = _summarize_articles(data.articles)
    trials_text   = _summarize_trials(data.trials)
    fda_text      = _summarize_fda(data.fda_approvals, data.adverse_events, data.drug_labels)

    prompt = f"""You are a senior pharmaceutical competitive intelligence analyst.
Synthesize the following real data retrieved from PubMed, ClinicalTrials.gov, and the FDA
into a structured 5-section intelligence report for this analyst query:

QUERY: "{data.query}"
DRUG CLASS / TARGET: {data.drug_class}
INDICATION: {data.indication}
TIME WINDOW: {data.time_window}
REPORT DATE: {datetime.now().strftime('%B %d, %Y')}

═══════════════════════════════════════════════════════
DATA FROM LITERATURE SCOUT (PubMed)
═══════════════════════════════════════════════════════
{articles_text}

═══════════════════════════════════════════════════════
DATA FROM TRIAL MONITOR (ClinicalTrials.gov)
═══════════════════════════════════════════════════════
{trials_text}

═══════════════════════════════════════════════════════
DATA FROM REGULATORY WATCH (openFDA)
═══════════════════════════════════════════════════════
{fda_text}

═══════════════════════════════════════════════════════
SYNTHESIS INSTRUCTIONS
═══════════════════════════════════════════════════════
Write exactly 5 sections. Each section MUST start with its exact label on its own line
(e.g. "## SECTION 1: RESEARCH LANDSCAPE"). Be factual — cite specific PMIDs, NCT IDs,
or application numbers wherever possible. Be concise (100–150 words per section).

## SECTION 1: RESEARCH LANDSCAPE
[Summarize the key research findings, publication trends, and most impactful papers. 
What are the dominant research themes? Which mechanisms/targets are most studied?]

## SECTION 2: CLINICAL PIPELINE
[Describe the clinical trial landscape: phases represented, leading sponsors, 
recruitment status, primary endpoints, and notable trials. What stages are most active?]

## SECTION 3: REGULATORY STATUS
[Summarize FDA approvals, rejection/hold history, key safety warnings (boxed warnings), 
and recent regulatory decisions. Who has approved products? Any pending applications?]

## SECTION 4: COMPETITIVE SUMMARY
[Identify the key players (companies), compare mechanisms of action, differentiation 
factors, and positioning. Who are the leaders and emerging challengers?]

## SECTION 5: STRATEGIC OUTLOOK
[Identify strategic gaps, unmet needs, competitive risks, and opportunities. 
What moves would be most impactful for a new entrant or incumbent player?]

Write the report now. Use professional analyst language. Be specific, not generic.
"""
    return prompt


# ---------------------------------------------------------------------------
# Response parsing
# ---------------------------------------------------------------------------

# Section header patterns — flexible to handle minor LLM formatting variations
_SECTION_PATTERNS = {
    "research_landscape": re.compile(
        r"##\s*SECTION\s*1[:\s]+RESEARCH\s+LANDSCAPE\s*\n(.*?)(?=##\s*SECTION\s*2|$)",
        re.DOTALL | re.IGNORECASE,
    ),
    "clinical_pipeline": re.compile(
        r"##\s*SECTION\s*2[:\s]+CLINICAL\s+PIPELINE\s*\n(.*?)(?=##\s*SECTION\s*3|$)",
        re.DOTALL | re.IGNORECASE,
    ),
    "regulatory_status": re.compile(
        r"##\s*SECTION\s*3[:\s]+REGULATORY\s+STATUS\s*\n(.*?)(?=##\s*SECTION\s*4|$)",
        re.DOTALL | re.IGNORECASE,
    ),
    "competitive_summary": re.compile(
        r"##\s*SECTION\s*4[:\s]+COMPETITIVE\s+SUMMARY\s*\n(.*?)(?=##\s*SECTION\s*5|$)",
        re.DOTALL | re.IGNORECASE,
    ),
    "strategic_outlook": re.compile(
        r"##\s*SECTION\s*5[:\s]+STRATEGIC\s+OUTLOOK\s*\n(.*?)$",
        re.DOTALL | re.IGNORECASE,
    ),
}


def parse_synthesis_response(
    raw_response: str,
    synthesis_input: SynthesisInput,
) -> IntelligenceReport:
    """
    Parse the LLM's raw text response into a structured IntelligenceReport.

    Uses regex section extraction with graceful fallback: if a section is not
    found (LLM hallucinated a different header format), the raw response is
    stored as `research_landscape` and the other sections are marked as
    "Parsing failed — see raw_response".
    """
    report = IntelligenceReport(
        query=synthesis_input.query,
        generated_at=datetime.now().isoformat(),
        drug_class=synthesis_input.drug_class,
        indication=synthesis_input.indication,
        raw_response=raw_response,
        data_sources={
            "pubmed_articles": len(synthesis_input.articles),
            "clinical_trials": len(synthesis_input.trials),
            "fda_approvals":   len(synthesis_input.fda_approvals),
            "adverse_events":  len(synthesis_input.adverse_events),
            "drug_labels":     len(synthesis_input.drug_labels),
        },
    )

    sections_found = 0
    for field_name, pattern in _SECTION_PATTERNS.items():
        match = pattern.search(raw_response)
        if match:
            content = match.group(1).strip()
            setattr(report, field_name, content)
            sections_found += 1

    # Fallback: if parsing failed completely, dump the whole response
    if sections_found == 0:
        report.research_landscape = (
            "⚠️  Section parsing failed. Full LLM output stored in raw_response field.\n\n"
            + raw_response[:500]
        )
        for field_name in list(_SECTION_PATTERNS.keys())[1:]:
            setattr(report, field_name, "See research_landscape / raw_response for full output.")

    return report
